### ISSUE TITLE
Bump pip version

### ISSUE THREAD

**Issue by hugohadfield** [pygae/galgebra#10]
We should put out a python3 compatible release and bump the version in pypi to give people access to the nnice work of @utensil

**Comment by utensil** [comment]
I'm ok with bumping pip version as is but I also would like to include some work in #9 to be merged first.

My work on #9 wasn't solely on documentation but also fixes a series of issues. The PR doesn't have much progress since last Sep due to my busy work  and also because I hit a wall that I could not fix the problems I found ( a few attempts since Sep but no success).

I can isolate some of the fixes to a new PR for you guys to review in the coming 2-3 days, if that sounds ok.

**Comment by utensil** [comment]
There's one more issue to discuss: the version number.

I'm seeing 4 versions ever released on https://pypi.org/project/galgebra/#history , namely 0.4.1, 0.4.2, 0.4.2.1, 0.4.2.2 . In my understanding of  https://semver.org/ , the releases before 1.0 is following 0.MAJOR.MINOR.PATCH, since this version will add Python 3 support, it seems that we can bump the MINOR, so the version number will be 0.4.3, is that right?

And `setup.py` is currently not specifying the version correctly (it says 0.4.1.1), and it states only 'Programming Language :: Python :: 2.7' is supported. These places needs to be updated in the version bump as well (just stating the obvious...).

**Comment by hugohadfield** [comment]
@utensil no worries, I think there is not a big rush! I have also been absolutely smothered in work and so have failed to get involved in this. I think I ended up pushing some of those versions into pypi just because I didn't know what I was doing with distribution... I think going to 0.4.3 makes sense

**Comment by hugohadfield** [comment]
Wrt the pull request I think the work looks fantastic and the docs also look awesome.

**Comment by hugohadfield** [comment]
@utensil I seem to have managed to get the pypi deployment to work just about with my credentials
https://pypi.org/manage/project/galgebra/releases/

**Comment by utensil** [comment]
> @utensil I seem to have managed to get the pypi deployment to work just about with my credentials
> https://pypi.org/manage/project/galgebra/releases/

Great! 

P.S. I'm a little confused by the failed runs on Travis: 

![image](https://user-images.githubusercontent.com/64258/52956642-be434200-33ca-11e9-9c39-90db674da997.png)
