### ISSUE TITLE
basis vectors not normalizing when `norm=True`

### ISSUE THREAD

**Issue by Greg1950** [pygae/galgebra#466]
The attached pdf file (ignore its first two pages) shows that normalization of the basis does not always occur when a geometric algebra is instantiated with parameter value `norm=True`.  Sometimes the basis normalizes and sometimes it does not.   

[basis vectors not normalizing.pdf](https://github.com/pygae/galgebra/files/5324768/basis.vectors.not.normalizing.pdf)

**Comment by eric-wieser** [comment]
Thanks for the report. Again, it would make things easier for us if you used as small an example as possible. I've extracted one for you, as:
```
from sympy import symbols, sin, cos
from galgebra.ga import Ga

R = symbols('R', positive=True)
theta, z = symbols('theta z', real=True)
Cyl2_coords = (theta, z)
p = (R*cos(theta), R*sin(theta), z)
Cyl2_OG = Ga('e', coords=Cyl2_coords, X=p, norm=False)
Cyl2_ON = Ga('e', coords=Cyl2_coords, X=p, norm=True)

display(Cyl2_OG.g)
display(Cyl2_ON.g)

**Comment by eric-wieser** [comment]
The results differ because of the value of [`.connect_flg`](https://galgebra.readthedocs.io/en/latest/generated/galgebra.metric.html#galgebra.metric.Metric.connect_flg)
```
>>>: E3_OG.connect_flg
True
>>> E3_ON.connect_flg
True
>>> Cyl2_OG.connect_flg
False
>>> Cyl2_ON.connect_flg
False
```
which results in `.de` not being calculated:

https://github.com/pygae/galgebra/blob/364b4e8497284aae3b0ec7af9cc1cea914aa8347/galgebra/metric.py#L464-L471

which results in `normalize_metric()` exiting early:

https://github.com/pygae/galgebra/blob/364b4e8497284aae3b0ec7af9cc1cea914aa8347/galgebra/metric.py#L568-L571

before it actually normalizes `g`:

https://github.com/pygae/galgebra/blob/364b4e8497284aae3b0ec7af9cc1cea914aa8347/galgebra/metric.py#L591-L595

I'm afraid I have no understanding of what this `connect_flg` or `de` stuff is supposed to do. @abrombo who wrote it originally might remember.

**Comment by eric-wieser** [comment]
Thankfully, I don't need to understand `connect_flg` or `de` to fix this issue, see above
